name: HAI tech Task CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.4]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry ${{ matrix.poetry-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==${{ matrix.poetry-version }}

    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
      run: python -m poetry install

    - name: Test with pytest & build coverage file
      run: |
        python -m poetry run python -m pytest --cache-clear --cov=app test/ > pytest-coverage.txt
    - name: Comment coverage on PR
      uses: coroo/pytest-coverage-commentator@v1.0.2

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.10
      with:
        pypi_token: ${{ secrets.PYPI_TEST_TOKEN }}
        repository_name: "testpypi"
        repository_url: "https://test.pypi.org/legacy/"